local statusline = {
  "%#DiffAdd#%{(mode()[0]=='n')?'  NORMAL ':''}",
  "%#DiffAdd#%{(mode()[0]=='c')?'   CMD   ':''}",
  "%#DiffText#%{(mode()[0]=='i')?'  INSERT ':''}",
  "%#DiffText#%{(mode()[0]=='t')?'   TERM  ':''}",
  "%#DiffDelete#%{(mode()[0]=='R')?'  RPLACE ':''}",
  "%#Search#%{(mode()[0]=='v')?'  VISUAL ':''}",
  "%#Search#%{(mode()[0]=='V')?'  V-LINE ':''}",
  [[%#Search#%{(mode()=="\<C-V>")?'  VBLOCK ':''}]],
  "%#Visual#",
  "%{&paste?'  PASTE ':''}",
  "%{&spell?'  SPELL ':''}",
  "%#CursorIM#",
  "%r",
  "%m",
  "%#Cursor#",
  "%#CursorLine#",
  " %t ",
  "%=",
  "%#CursorLine#",
  [[%{luaeval('#vim.lsp.buf_get_clients() > 0') ? luaeval("require('lsp-status').status()") : ''}]],
  " %y ",
  "%#CursorIM#",
  " %3l:%-2c ",
  "%#Function#",
  " %3p%% ",
}

vim.o.statusline = table.concat(statusline)
